// styles
import Dashboard from '../../components/dashBoard';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function DashBoardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Dashboard>
      {children}
    </Dashboard>
  );
}
